name: "deploiement github

on:
  push:
    branches: [ master ]
    tags:
      - TP3-V*
  pull_request:
    branches: [ master ]
    tags:
      - TP3-V*

env:
  PROJECT_PATH: TP214E/TP214E.csproj

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH  }}
      
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH  }} -c Release --no-restore
      
    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH  }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ github.ref }}
        release_name: ${{ github.ref }}
        
    - uses: csexton/release-asset-action@v2
      with:
        github-token ${{ secrets.GITHUB_TOKEN }}
        pattern: TP214E/bin/release/netcoreapp3.1/win-x64/publish/*.exe
        release-url: ${{ steps.create_release.outputs.upload_url }}
